// vim:ft=groovy et ts=4 sts=4 sw=4

stage('prepare and validate') {
    if (IS_RELEASE.toBoolean() && SHA.length() != 40) {
        error('Must have a specific SHA1 when IS_RELEASE=true')
    }
    if (!_INTERNAL_OK_.toBoolean()) {
        error('Expected _INTERNAL_OK_ to be set')
    }

    node('centos7') {
        deleteDir()
        
        sh("""
wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
tar -xzvf chruby-0.3.9.tar.gz
cd chruby-0.3.9/
sudo make install

wget -O ruby-install-0.7.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz
tar -xzvf ruby-install-0.7.0.tar.gz
cd ruby-install-0.7.0/
sudo make install
""")
        sh("""
ruby-install
""")
        sh("""
ruby-install ruby 2.7.1
""")

        sh("env")
        sh("ruby --version")

        dir("ruby-sdk") {
            checkout([
                $class: 'GitSCM',
                branches: [[name: '$SHA']],
                extensions: [[
                    $class: 'SubmoduleOption',
                    disableSubmodules: false,
                    parentCredentials: true,
                    recursiveSubmodules: true,
                ]],
                userRemoteConfigs: [[refspec: "$GERRIT_REFSPEC", url: '$REPO', poll: false]]])
        }
        stash(includes: 'ruby-sdk/', name: 'ruby-sdk', useDefaultExcludes: false)
    }
}

stage('success') {
    echo "things are great!"
}
